### ISSUE TITLE
printh

### ISSUE THREAD

**Issue by farvardin** [gamax92/picolove#1]
printh was removed from the original picolove. It means when you have a w.i.p. and you try to export it to löve, if will fail.

**Comment by josefnpat** [comment]
@farvardin it should be as easy as adding `printh = print` before the print statement is redefined for pico8's draw command.

Tell us if that works, so someone can make a PR.

**Comment by josefnpat** [comment]
I was able to easily recreate it - making a PR

**Comment by gamax92** [comment]
My apologies ^^;
should be fixed up by 595742a22e3b25767e4f1a0b1af772e2e09291fd

**Comment by josefnpat** [comment]
@gamax92 

`api.printh = print`

Is technically not correct:

![image](https://cloud.githubusercontent.com/assets/646162/15953424/517a709a-2e90-11e6-987b-f6d7da5ac914.png)

**Comment by farvardin** [comment]
thanks a lot!

**Comment by gamax92** [comment]
I know it's not correct but I quite like the not broken debugging tool, since that's what printh is, a debugging tool. If PICO-8's behaviour is desired, it can be added in instead if you'd like.
