### ISSUE TITLE
GLES error on Raspberry Pi

### ISSUE THREAD

**Issue by vanfanel** [gamax92/picolove#14]
Hi, I have opened a similar issue on the branch: https://github.com/picolove/picolove
but I believe this fork is more updated.

I have been trying to run picolove on the Raspberry Pi platform.
It's running raspbian and SDL2 is built with GLES2 support. Many SDL2 games work on it using the GLES2 renderer.
On the LÖVE side of things, the SuperToast demo works perfectly too.
Howeve, picolove gives me this:

```
pi@raspberrypi:~/pico $ love picolove/
Error: Cannot link shader program object:
ERROR:CUSTOM-14 (fragment shader, line 5) Support for indexing array/vector/matrix with a non-constant is not mandated in the fragment shader
stack traceback:
    [C]: in function 'newShader'
    main.lua:244: in function 'load'
    main.lua:659: in function <main.lua:647>
    [C]: in function 'xpcall'

```

Any idea on what could be wrong here?

thanks!

**Comment by gamax92** [comment]
Ahh, seems that error (or atleast the message itself) is videocore specific, I don't have any rpi's around myself but I'll try to look into the error.

I know that for picolove on my android phone (also uses GLES) I don't get this error

**Comment by vanfanel** [comment]
@gamax92 : It seems that someone else found this when trying to pass a non-constant uniform array in GLES on the VideoCore:

https://www.raspberrypi.org/forums/viewtopic.php?f=68&t=28720

I guess it's a "limit" of the GLES implementation on the Pi. Do you think a workaround would be possible?

EDIT: A workaround and the cause of this limitation on some platforms is mentioned here:
http://stackoverflow.com/questions/13315334/non-constant-index-into-uniform-array-cg-shader

It seems that doing 
`vec4(palette[index]/255.0, 0.0, 0.0, 1.0)`
is the problem.

It's further explained here: 

http://gamedev.stackexchange.com/questions/77854/how-can-i-reliably-implement-gpu-skinning-in-android

It seems that, even if it's working on iPhone, it could be failing on other GLES devices, not only the Pi.

**Comment by gamax92** [comment]
Eww ... I guess I have to use a large if chain with constant indexes then.

**Comment by gamax92** [comment]
Apologies for the delay, Can you run a small Love2D test on your Pi `print(love.graphics.getRendererInfo())` and report back what that gives.
A solution has been worked on for this

**Comment by vanfanel** [comment]
@gamax92 : 

This is what I get:

`OpenGL ES  OpenGL ES 2.0   Broadcom    VideoCore IV HW
`

Hope it helps :)

**Comment by gamax92** [comment]
Not quite ... that should have been tab delimited.
I'm guessing that's, OpenGL ES | OpenGL ES 2.0 | Broadcom | VideoCore IV HW

```
local name, version, vendor, device = love.graphics.getRendererInfo()
print("Name: "..name.."\nVersion: "..version.."\nVendor: "..vendor.."\nDevice: "..device)
```

Same thing, but with the parts split out for easier readability, just to make sure.

EDIT: Yeah that should be it, research with that line confirms that. Pushed a fix into the repo that should solve this for you, test it out?

**Comment by vanfanel** [comment]
@gamax92 : The fix seems to work, yes, I can now get to the Pico-8 commandine.
However, if I try to load a game in .p8.png, I get:

```
pi@raspberrypi:~/love2d $ love picolove 28450.p8.png 
Using proprietary Broadcom video driver shader fixes
Loading 28450.p8.png
Error: cart.lua:266: Unable to open: 28450.p8.png
stack traceback:
    [C]: in function 'error'
    cart.lua:266: in function 'load_p8'
    main.lua:126: in function '_load'
    main.lua:339: in function 'load'
    main.lua:706: in function <main.lua:694>
    [C]: in function 'xpcall'


```

Any ideas on what am I doing wrong?

**Comment by gamax92** [comment]
Love2D has a filesystem sandbox, and can only see files that are inside the directory (or .love archive) containing main.lua and further, or it's own save directory at ~/.local/share/love/picolove/

You have to put 28450.p8.png inside your picolove folder for Love2D to be able to see it.

I might add in additional code that'll try to read the file using normal Lua io api.

**Comment by vanfanel** [comment]
@gamax92 : Now it works at last, yes, it can see the carts inside picolove directory :)
So, for the first time, I can see what Pico-8 looks like on a Raspberry Pi!
However, image is small on my 1360x768 monitor. Other love2d games are fullscreen (Super Toaster example is fullscreen). I have been playing with the scaling parameters in picolove/main.lua but I see no difference: only a tiny part of the screen is used.
Note that, on the Pi, SDL2 (and hence Love2D) runs X-less: no windowing bloatware involved. It al runs in console mode.

EDIT: Modifying the "scale=4" line to "scale=6" gets me something way bigger :dancer: 

However, sound effects seem to be very delayed. Is that what https://github.com/gamax92/picolove/issues/11 is about?

**Comment by gamax92** [comment]
You might try lowering __buffer_size to 512 or __buffer_count to 4
I've not found optimal values for the audio settings. Feel free to play around with that and report on #11 on what works good for you with minimal audio stutter.

And since the original issue of GLES shaders has been fixed, issue will be marked as closed
