### ISSUE TITLE
Can't properly load Jelpi

### ISSUE THREAD

**Issue by makinori** [gamax92/picolove#15]
nocart.p8 runs totally fine but when I type `load jelpi.p8` it returns

![ejwnyeeohcamamc_8acklyl4g4iejuoj1hjy7n935zgf9frlrwoxawmf2i6rug96cpdysi7m5cqxhumnvigkxltfucoanaidn8ajpecjcahrhxlxi_m2kdxzv556vn6rbrwo7w8ibsln](https://cloud.githubusercontent.com/assets/8362329/18613149/5021f3b0-7d6b-11e6-8c59-2b0692f48f76.png)

So instead I change the main.lua file so it loads jelpi.p8 on startup 
`line 293: _load(argv[2] or 'jelpi.p8')` and then it returns

![ejwfwveogyamanc7caaknqxxngqjmikltgyfy-6-977mmzfzzke6zapytyk8dyvkm7dqg3o7ah6n2mi3znvcjrt2fubpgkjzerdkkygqeen6jzdcwnh71s8bnv7u_ol29gz-fwbmits](https://cloud.githubusercontent.com/assets/8362329/18613155/8266b14e-7d6b-11e6-843e-1cfe9d4c36b8.png)

That doesn't work either. I change the main.lua file again so it loads jelpi.p8.png instead
`line 293: _load(argv[2] or 'jelpi.p8.png')` and that returns

![ejwfwdenhcamanbdgibioqjuq5cgusmbmvu43o733le941abokt63ad2c2yeu57ci9wik3o9s-rn1jkfsciph09pmgexwtub49fr9eseglhgg50nirhcrgfhbvfjt9o9vfx7awc9it4](https://cloud.githubusercontent.com/assets/8362329/18613161/9d17efee-7d6b-11e6-8fa7-e8a270a0065b.png)

With the .png file it plays the first part of the music but crashes quickly after. 

Also, to mention, picolove/picolove can't load jelpi.p8 either but it can load the .png version perfectly.

**Comment by gamax92** [comment]
Text carts on Windows should now be supported, can you retest to make sure?

**Comment by gamax92** [comment]
Should be fixed by 5a4d119fce1891c85e6c4b906439e0fbcd04587c and fe93fb51d99867c375b367caa88acdbf40c59e6b

**Comment by makinori** [comment]
Sorry I didn't answer back. Totally works now! Awesome.
