### ISSUE TITLE
Error: cart.lua:332: 640 + 4096 != 8192

### ISSUE THREAD

**Issue by tobiasvl** [gamax92/picolove#24]
I get the following error when trying to run [this cart](https://github.com/tobiasvl/picolarium/blob/master/picolarium.p8):

```
Error: cart.lua:332: 640 + 4096 != 8192
stack traceback:
        [string "boot.lua"]:637: in function <[string "boot.lua"]:633>
        [C]: in function 'assert'
        cart.lua:332: in function 'load_p8'
        main.lua:140: in function '_load'
        main.lua:348: in function 'load'
        main.lua:719: in function <main.lua:711>
        [C]: in function 'xpcall'
        [string "boot.lua"]:650: in function <[string "boot.lua"]:639>
        [C]: in function 'xpcall'
```

This is an assertion that `tiles+shared==128*64`, but in my cart apparently `tiles==640` and `shared==4096`, and `640+4096==4736`. Not sure how that's possible though.

**Comment by hsandt** [comment]
Same issue. I commented the assert out but now I get

> Error loading lua: Games/game.p8:124: unexpected symbol near '<eof>'
> 
> Traceback
> 
> [C]: in function 'error'
> cart.lua:429: in function 'load_p8'
> main.lua:140: in function '_load'
> ...
>

**Comment by Liquidream** [comment]
Same, for several of my games (but not all).
Not sure what about the cart code triggers it tho...

**Comment by gamax92** [comment]
Sorry about the delay on this, been kinda busy. Should be fixed now.
