### ISSUE TITLE
Should I update the link to picolove?

### ISSUE THREAD

**Issue by felipebueno** [gamax92/picolove#3]
Hi, @gamax92 

As the original picolove repository appears to be dead, I'm thinking of changing the link on the [awesome-PICO-8}](https://github.com/felipebueno/awesome-PICO-8) to this repo.

Do you think it's a good a idea?

**Comment by josefnpat** [comment]
I would think so - @gamax92's is the official continuation

**Comment by felipebueno** [comment]
Done 👍
