### ISSUE TITLE
Extended character glyphs not supported

### ISSUE THREAD

**Issue by gingerbeardman** [gamax92/picolove#7]
They are encoded as ASCII characters 128 through 153

See: http://www.lexaloffle.com/bbs/?tid=3217

![pico-8_4](https://cloud.githubusercontent.com/assets/49612/17409564/b89ca4b6-5a67-11e6-800a-5a2c207ba8b4.png)

**Comment by gamax92** [comment]
I'll get to this, busy with other projects at the moment though ...

**Comment by gamax92** [comment]
Fixed in 05e8ba8401df76bb765ea38a5003cd8690db2133
